### PR TITLE
Fixes #221 "Error: Command '\FA' already defined!"

### LINKED ISSUE #221: Compilation fails after the latest TexLive update
Good day,

I just ran `tlmgr update --all` and the same file I compiled the moment before started showing the following error:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! LaTeX error: "xparse/command-already-defined"
!
! Command '\FA' already defined!
!
! See the LaTeX3 documentation for further information.
!
! For immediate help type H <return>.
!...............................................

l.166 \newfontfamily
                    \headerfont[
```

It seems to work if I comment out the `\newfontfamily\FA{FontAwesome}` line in `awesome-cv.cls`.

### PR DESCRIPTION
**Pull request by FloThinksPi**
Fixes Compilation Error when commenting out the \newfont: xdvipdfmx:fatal: pdf_ref_obj(): passed invalid object.
As well als the Compilation Error: LaTeX3 Error: Command '\FA' already defined!For immediate help type H <return>.

Fixes #221 by unsetting /FA before redefining it.

In Contrary to other Pull Reqests #233 #235 and #236 i found, fontawsome works with this change.
Tested with MikTex on Windows.

### CODE REVIEW

**Comment by FloThinksPi** [comment]
@posquit0 Is this Repo maintained ?

**Comment by jbelsky** [comment]
Just confirming that this fix worked for LaTeX3 on Windows (TeX Live 2018) with the same error:
> Command '\FA' already defined!

Thanks @FloThinksPi for providing an easy solution, and thanks @posquit0 for providing a great resume template.

**Comment by jakevossen5** [comment]
This works for me, should probably be merged.

**Comment by bob-swinkels** [comment]
Works for me as well, Mac OS Catalina with MacTex

**Comment by rahulthewall** [comment]
Works for me as well, Win10 and texlive.

**Comment by gigerbytes** [comment]
Works for me (ubuntu 20.04 & OSX High Sierra)

**Comment by firaja** [comment]
### Should be merged
It works on macOS Catalina, XeTeX 3.14159265-2.6-0.999992

**Comment by OJFord** [comment]
Thank you - I think many of us have made this or similar fixes over the years as posquit0's had other priorities. I have push access now to help maintain Awesome-CV; so I went with my old PR for this (#235/#344) for no reason other than my own familiarity, that I know it's been working for me.

Please do ping me/open another PR if something's still not right or I missed something though! Cheers.
